// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8iccpZJ5R0y45m6n849MKEDnz2j_Nkc',
    appId: '1:853627377404:web:9b45b9275081737a6c2979',
    messagingSenderId: '853627377404',
    projectId: 'e-chat-ea952',
    authDomain: 'e-chat-ea952.firebaseapp.com',
    storageBucket: 'e-chat-ea952.firebasestorage.app',
    measurementId: 'G-PM5ZVGB3V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ExzNPz0AMcXoqr8a7J7L8yoygXGQ3cY',
    appId: '1:853627377404:android:ae071bfc1f9c5aeb6c2979',
    messagingSenderId: '853627377404',
    projectId: 'e-chat-ea952',
    storageBucket: 'e-chat-ea952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0N9smczu-S8YIWDiSjXLsQr2diFw5z80',
    appId: '1:853627377404:ios:766e31daa228b1376c2979',
    messagingSenderId: '853627377404',
    projectId: 'e-chat-ea952',
    storageBucket: 'e-chat-ea952.firebasestorage.app',
    iosBundleId: 'com.example.eChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0N9smczu-S8YIWDiSjXLsQr2diFw5z80',
    appId: '1:853627377404:ios:766e31daa228b1376c2979',
    messagingSenderId: '853627377404',
    projectId: 'e-chat-ea952',
    storageBucket: 'e-chat-ea952.firebasestorage.app',
    iosBundleId: 'com.example.eChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF8iccpZJ5R0y45m6n849MKEDnz2j_Nkc',
    appId: '1:853627377404:web:f896a199300676536c2979',
    messagingSenderId: '853627377404',
    projectId: 'e-chat-ea952',
    authDomain: 'e-chat-ea952.firebaseapp.com',
    storageBucket: 'e-chat-ea952.firebasestorage.app',
    measurementId: 'G-27N80EHC78',
  );

}